version: '3.1'

services:

  db:
    image: postgres
    restart: always
    networks:
      - pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    networks:
      - pg
    ports:
      - 8080:8080

networks:
  pg:
    driver: bridge
